import Head from "next/head";
import Components from "../components/podstrony/blog/Importblog";
import { Row, Col, Container, Card } from "reactstrap";
import img1 from "../assets/images/blog/blog-home/img3.jpg";
import Image from "next/image";
import Banner from "../components/banner/Banner";
<Banner data="Aplikacje webowe" pageone="Nowoczesna grafika
" pagetwo="Popraw sprzedaz" pagethree="Stałe wsparcie"
/>
export default function Blog({ posts }) {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <div>
  
<Components posts={posts}/>    
</div>
  </div>
 );
}


export async function getStaticProps(context) {
  const res = await fetch('https://gruca.j.pl/wp-json/wp/v2/posts')
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}