import Head from "next/head";
import Components from "../components/podstrony/kontakt/Importkontakt";

export default function Kontakt() {
  return (
    <div>
      <Head>
        <title>kontakt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Components />
    </div>
  );
}
