import Head from "next/head";
import Components from "../components/pages/Importpage";

export default function Pages() {
  return (
    <div>
      <Head>
        <title>Strony www z Effective Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Components />
    </div>
  );
}
